site_name: Jonathan's Blog
site_description: A blog for Jonathan to post his thoughts
site_url: https://mydomain.org/mysite

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - navigation.footer

plugins:
  - search
  - blog:
      blog_dir: .
      archive: false
      categories_allowed:
        - Tech
        - Books
        - Movies

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jonathan343
    - icon: fontawesome/brands/github
      link: https://github.com/jonathan343
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/jonathang09_